using Microsoft.OpenApi; 
namespace Hive_Movie.Configuration;

public static class OpenApiConfig
{
    public static IServiceCollection AddOpenApiDocumentation(this IServiceCollection services)
    {
        _ = services.AddOpenApi(static options =>
        {
            // 1. Customize the Title, Version, and Description
            options.AddDocumentTransformer((document, context, cancellationToken) =>
            {
                document.Info = new OpenApiInfo
                {
                    Title = "The Hive - Movie & Ticketing API",
                    Version = "v1",
                    Description = "The core microservice handling movie catalogs, physical cinema layouts, and highly concurrent seat reservations.",
                    Contact = new OpenApiContact
                    {
                        Name = "Hive Architecture Team",
                        Email = "naveenrameshcud@gmail.com"
                    }
                };
                return Task.CompletedTask;
            });

            // 2. Configure the JWT Bearer Authentication UI (Updated for .NET 10 API)
            _ = options.AddDocumentTransformer(static (document, context, cancellationToken) =>
            {
                document.Components ??= new OpenApiComponents();

                // 1. Create the security scheme using the new .NET 10 structure
                var bearerScheme = new OpenApiSecurityScheme
                {
                    Type = SecuritySchemeType.Http,
                    Scheme = "bearer",
                    BearerFormat = "JWT",
                    Description = "Enter the JWT token generated by the Kotlin Hive-Identity service."
                };

                // 2. Add it to the document components using the new AddComponent method
                document.AddComponent("Bearer", bearerScheme);

                // 3. Create a security requirement using the new OpenApiSecuritySchemeReference
                var securityRequirement = new OpenApiSecurityRequirement
                {
                    [new OpenApiSecuritySchemeReference("Bearer", document)] = []
                };

                // 4. Apply the requirement globally using the renamed 'Security' property
                document.Security ??= [];
                document.Security.Add(securityRequirement);

                return Task.CompletedTask;
            });
        });

        return services;
    }
}