using Microsoft.OpenApi;
namespace Hive_Movie.Configuration;

public static class OpenApiConfig
{
    public static IServiceCollection AddOpenApiDocumentation(this IServiceCollection services)
    {
        _ = services.AddOpenApi(static options =>
        {
            // 1. Customize the Title, Version, and Description
            options.AddDocumentTransformer((document, _, _) =>
            {
                document.Info = new OpenApiInfo
                {
                    Title = "The Hive - Movie & Ticketing API",
                    Version = "v1",
                    Description = "The core microservice handling movie catalogs, physical cinema layouts, and highly concurrent seat reservations.",
                    License = new OpenApiLicense
                    {
                        Name = "MIT License", Url = new Uri("https://github.com/Naveen2070/Hive-Movie/blob/main/LICENSE.txt")
                    },
                    Contact = new OpenApiContact
                    {
                        Name = "Hive Architecture Team", Email = "naveenrameshcud@gmail.com"
                    }
                };

                document.Tags = new HashSet<OpenApiTag>
                {
                    new()
                    {
                        Name = "Cinemas Management",
                        Description = "Manage physical cinema locations, including creation, updates, and global approval statuses."
                    },
                    new()
                    {
                        Name = "Auditoriums Management", Description = "Manage cinema auditoriums and validate complex seating grid layouts."
                    },
                    new()
                    {
                        Name = "Movies Catalog", Description = "Global catalog of movies available across all cinemas."
                    },
                    new()
                    {
                        Name = "Showtimes Management", Description = "Schedule movies into specific auditoriums with pricing and availability tracking."
                    },
                    new()
                    {
                        Name = "Ticketing & Checkout",
                        Description = "Process highly concurrent atomic seat reservations and asynchronous payment webhooks."
                    }
                };

                return Task.CompletedTask;
            });

            // 2. Configure the JWT Bearer Authentication UI
            _ = options.AddDocumentTransformer(static (document, _, _) =>
            {
                document.Components ??= new OpenApiComponents();

                // 1. Create the security scheme
                var bearerScheme = new OpenApiSecurityScheme
                {
                    Type = SecuritySchemeType.Http,
                    Scheme = "bearer",
                    BearerFormat = "JWT",
                    Description = "Enter the JWT token generated by the Kotlin Hive-Identity service."
                };

                // 2. Add it to the document components
                document.AddComponent("Bearer", bearerScheme);

                // 3. Create a security requirement
                var securityRequirement = new OpenApiSecurityRequirement
                {
                    [new OpenApiSecuritySchemeReference("Bearer", document)] = []
                };

                // 4. Apply the requirement globally
                document.Security ??= [];
                document.Security.Add(securityRequirement);

                return Task.CompletedTask;
            });
        });

        return services;
    }
}